name: Terraform Plan

on:
  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/terraform-plan.yml"

permissions:
  contents: read

env:
  AWS_ACCESS_KEY_ID: testing
  AWS_SECRET_ACCESS_KEY: testing
  AWS_DEFAULT_REGION: us-east-1

jobs:
  terraform-dev:
    name: Terraform Dev Validation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/envs/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Prepare CI configuration
        run: |
          mv backend.tf backend.tf.disabled
          cp terraform.tfvars.example terraform.tfvars

      - name: Terraform Format Check
        run: terraform fmt -check -recursive ../../

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

       - name: Terraform Plan
  run: terraform plan -refresh=false -lock=false -var="ci_mode=true"

  terraform-prod:
    name: Terraform Prod Validation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/envs/prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Prepare CI configuration
        run: |
          mv backend.tf backend.tf.disabled
          cp terraform.tfvars.example terraform.tfvars

      - name: Terraform Format Check
        run: terraform fmt -check -recursive ../../

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

       - name: Terraform Plan
  run: terraform plan -refresh=false -lock=false -var="ci_mode=true"